site_name: D233 - MLflow Model Registry | Enterprise Technical Specification
site_description: Gestión de versiones, etapas y ciclo de vida de modelos predictivos.
site_author: Engineering Core Team

theme:
  name: material
  language: es
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: amber
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo

nav:
  - Visión General y Resumen Ejecutivo: index.md
  - Arquitectura del Model Registry: architecture.md