site_name: D206 - Code Coverage Enforcer
site_description: Auditoría estricta de cobertura de código para módulos analíticos.
site_author: Oliver
theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange

nav:
  - Inicio: index.md
  - Arquitectura: architecture.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.superfences