site_name: D209 - DuckDB Secret Manager Integration
site_description: Gestión segura de credenciales y rutas de almacenamiento remoto para DuckDB.
site_author: Oliver
theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange

nav:
  - Inicio: index.md
  - Arquitectura: architecture.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.superfences