site_name: D204 - Docker Compose Analytics Stack
site_description: Documentación de microservicios analíticos con FastAPI y Docker Compose.
site_author: Oliver
theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange

nav:
  - Inicio: index.md
  - Arquitectura: architecture.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.superfences