site_name: D212 - DuckDB & MotherDuck Cloud Sync
site_description: Sincronización híbrida de bases de datos analíticas locales con la nube de MotherDuck.
site_author: Oliver
theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: teal
      accent: deep orange

nav:
  - Inicio: index.md
  - Arquitectura: architecture.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.superfences